## 1. Import Required Libraries

In [ ]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## 2. Load the Titanic Dataset

In [ ]:
df = pd.read_csv("/content/titanic_raw.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (891, 12)

## 3. Explore the Dataset

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 4. Check Missing Values

In [ ]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## 5. Check Duplicate Rows

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

## 6. Statistical Summary

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## 7. Create a Copy of the Dataset

In [ ]:
cleaned_df = df.copy()

print("Copy created successfully!")

Copy created successfully!

## 8. Remove Duplicate Rows

In [ ]:
before = len(cleaned_df)

cleaned_df = cleaned_df.drop_duplicates()

after = len(cleaned_df)

print("Rows before:", before)
print("Rows after:", after)
print("Duplicates removed:", before - after)

Rows before: 891
Rows after: 891
Duplicates removed: 0

## 9. Handle Missing Values in Age

In [ ]:
age_median = cleaned_df["Age"].median()

print("Median Age:", age_median)

cleaned_df["Age"] = cleaned_df["Age"].fillna(age_median)

print("Missing Age after cleaning:",
      cleaned_df["Age"].isnull().sum())

Median Age: 28.0
Missing Age after cleaning: 0

### 10. Handle Missing Values in Embarked

In [ ]:
embarked_mode = cleaned_df["Embarked"].mode()[0]

print("Mode of Embarked:", embarked_mode)

cleaned_df["Embarked"] = cleaned_df["Embarked"].fillna(embarked_mode)

print("Missing Embarked after cleaning:",
      cleaned_df["Embarked"].isnull().sum())

Mode of Embarked: S
Missing Embarked after cleaning: 0

## 11. Standardize Text Values

In [ ]:
cleaned_df["Sex"] = cleaned_df["Sex"].str.strip().str.lower()
cleaned_df["Embarked"] = cleaned_df["Embarked"].str.strip().str.upper()

print("Text values standardized successfully!")

Text values standardized successfully!

## 12. Remove Cabin Column

In [ ]:
cleaned_df = cleaned_df.drop(columns=["Cabin"])

print("Cabin column removed.")
print("New shape:", cleaned_df.shape)

Cabin column removed.
New shape: (891, 11)

## 13. Final Data Quality Validation

In [ ]:
print("FINAL DATA QUALITY CHECK")
print("------------------------")

print("\nMissing values:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows:",
      cleaned_df.duplicated().sum())

print("\nDataset shape:",
      cleaned_df.shape)

FINAL DATA QUALITY CHECK
------------------------

Missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Duplicate rows: 0

Dataset shape: (891, 11)

## 14. Export the Cleaned Dataset

In [ ]:
cleaned_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [ ]:
cleaned_df.to_csv("cleaned_titanic.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## 15. Download the Cleaned Dataset

In [ ]:
from google.colab import files

files.download("cleaned_titanic.csv")

## 16. Final Cleaned Dataset

In [ ]:
print("FINAL CLEANED DATASET")
print("--------------------")
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())

display(cleaned_df.head(10))

FINAL CLEANED DATASET
--------------------
Rows: 891
Columns: 11
Missing values: 0
Duplicate rows: 0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C