In [5]:

from google.colab import files

uploaded = files.upload()

Saving northwind.sqlite to northwind.sqlite

In [6]:

import sqlite3
import pandas as pd

db_file = next(iter(uploaded.keys()))
conn = sqlite3.connect(db_file)

print("Northwind database connected successfully!")

Northwind database connected successfully!

In [7]:

tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name
""", conn)

display(tables)

                    name
0             Categories
1   CustomerCustomerDemo
2   CustomerDemographics
3              Customers
4    EmployeeTerritories
5              Employees
6          Order Details
7                 Orders
8               Products
9                Regions
10              Shippers
11             Suppliers
12           Territories
13       sqlite_sequence

In [8]:

customers = pd.read_sql_query(
    "SELECT * FROM Customers",
    conn
)

print("Total records:", len(customers))
display(customers.head(10))
print("Columns:", customers.columns.tolist())

Total records: 93

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
5,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,Western Europe,68306,Germany,0621-08460,0621-08924
6,BLONP,Blondesddsl père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,Western Europe,67000,France,88.60.15.31,88.60.15.32
7,BOLID,Bólido Comidas preparadas,Martín Sommer,Owner,"C/ Araquil, 67",Madrid,Southern Europe,28023,Spain,(91) 555 22 82,(91) 555 91 99
8,BONAP,Bon app',Laurence Lebihan,Owner,"12, rue des Bouchers",Marseille,Western Europe,13008,France,91.24.45.40,91.24.45.41
9,BOTTM,Bottom-Dollar Markets,Elizabeth Lincoln,Accounting Manager,23 Tsawassen Blvd.,Tsawassen,North America,T2F 8M4,Canada,(604) 555-4729,(604) 555-3745

Columns: ['CustomerID', 'CompanyName', 'ContactName', 'ContactTitle', 'Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone', 'Fax']

In [9]:

import pandas as pd

customers = pd.read_sql_query(
    "SELECT * FROM Customers",
    conn
)

print("Total customer records:", len(customers))
print("Column names:", customers.columns.tolist())

display(customers.head(10))

Total customer records: 93
Column names: ['CustomerID', 'CompanyName', 'ContactName', 'ContactTitle', 'Address', 'City', 'Region', 'PostalCode', 'Country', 'Phone', 'Fax']

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
5,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,Western Europe,68306,Germany,0621-08460,0621-08924
6,BLONP,Blondesddsl père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,Western Europe,67000,France,88.60.15.31,88.60.15.32
7,BOLID,Bólido Comidas preparadas,Martín Sommer,Owner,"C/ Araquil, 67",Madrid,Southern Europe,28023,Spain,(91) 555 22 82,(91) 555 91 99
8,BONAP,Bon app',Laurence Lebihan,Owner,"12, rue des Bouchers",Marseille,Western Europe,13008,France,91.24.45.40,91.24.45.41
9,BOTTM,Bottom-Dollar Markets,Elizabeth Lincoln,Accounting Manager,23 Tsawassen Blvd.,Tsawassen,North America,T2F 8M4,Canada,(604) 555-4729,(604) 555-3745

In [10]:

query1 = """
SELECT *
FROM Customers
WHERE Country = 'Germany';
"""

result1 = pd.read_sql_query(query1, conn)
display(result1)
print("Total matching records:", len(result1))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,Western Europe,68306,Germany,0621-08460,0621-08924
2,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,Western Europe,52066,Germany,0241-039123,0241-059428
3,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,München,Western Europe,80805,Germany,089-0877310,089-0877451
4,KOENE,Königlich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,Western Europe,14776,Germany,0555-09876,None
5,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,Western Europe,60528,Germany,069-0245984,069-0245874
6,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,Western Europe,04179,Germany,0342-023176,None
7,OTTIK,Ottilies Käseladen,Henriette Pfalzheim,Owner,Mehrheimerstr. 369,Köln,Western Europe,50739,Germany,0221-0644327,0221-0765721
8,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstraße 10,Cunewalde,Western Europe,01307,Germany,0372-035188,None
9,TOMSP,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695
10,WANDK,Die Wandernde Kuh,Rita Müller,Sales Representative,Adenauerallee 900,Stuttgart,Western Europe,70563,Germany,0711-020361,0711-035428

Total matching records: 11

In [11]:

query2 = """
SELECT *
FROM Customers
WHERE City = 'London';
"""

result2 = pd.read_sql_query(query2, conn)
display(result2)
print("Total matching records:", len(result2))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,British Isles,EC2 5NT,UK,(171) 555-1212,None
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,British Isles,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,British Isles,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,British Isles,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,British Isles,OX15 4NB,UK,(171) 555-1717,(171) 555-5646

Total matching records: 6

In [12]:

query3 = """
SELECT *
FROM Customers
WHERE Country <> 'Germany';
"""

result3 = pd.read_sql_query(query3, conn)
display(result3)
print("Total matching records:", len(result3))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
1,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
2,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
3,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
4,BLONP,Blondesddsl père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,Western Europe,67000,France,88.60.15.31,88.60.15.32
...,...,...,...,...,...,...,...,...,...,...,...
75,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,Scandinavia,90110,Finland,981-443655,981-443655
76,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,South America,08737-363,Brazil,(14) 555-8122,None
77,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,North America,98128,USA,(206) 555-4112,(206) 555-4115
78,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,Scandinavia,21240,Finland,90-224 8858,90-224 8858
79,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,Eastern Europe,01-012,Poland,(26) 642-7012,(26) 642-7012

Total matching records: 80

In [13]:

query4 = """
SELECT *
FROM Customers
WHERE Country = 'Germany'
AND City = 'Berlin';
"""

result4 = pd.read_sql_query(query4, conn)
display(result4)
print("Total matching records:", len(result4))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545

Total matching records: 1

In [14]:

query5 = """
SELECT *
FROM Customers
WHERE City = 'London'
OR City = 'Paris';
"""

result5 = pd.read_sql_query(query5, conn)
display(result5)
print("Total matching records:", len(result5))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
1,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,British Isles,EC2 5NT,UK,(171) 555-1212,None
2,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,British Isles,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
3,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,British Isles,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
4,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,British Isles,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
5,PARIS,Paris spécialités,Marie Bertrand,Owner,"265, boulevard Charonne",Paris,Western Europe,75012,France,(1) 42.34.22.66,(1) 42.34.22.77
6,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,British Isles,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
7,SPECD,Spécialités du monde,Dominique Perrier,Marketing Manager,"25, rue Lauriston",Paris,Western Europe,75016,France,(1) 47.55.60.10,(1) 47.55.60.20

Total matching records: 8

In [15]:

query6 = """
SELECT *
FROM Customers
WHERE Country IN ('UK', 'Germany', 'France');
"""

result6 = pd.read_sql_query(query6, conn)
display(result6)
print("Total matching records:", len(result6))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
2,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,Western Europe,68306,Germany,0621-08460,0621-08924
3,BLONP,Blondesddsl père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,Western Europe,67000,France,88.60.15.31,88.60.15.32
4,BONAP,Bon app',Laurence Lebihan,Owner,"12, rue des Bouchers",Marseille,Western Europe,13008,France,91.24.45.40,91.24.45.41
5,BSBEV,B's Beverages,Victoria Ashworth,Sales Representative,Fauntleroy Circus,London,British Isles,EC2 5NT,UK,(171) 555-1212,None
6,CONSH,Consolidated Holdings,Elizabeth Brown,Sales Representative,Berkeley Gardens 12 Brewery,London,British Isles,WX1 6LT,UK,(171) 555-2282,(171) 555-9199
7,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,Western Europe,52066,Germany,0241-039123,0241-059428
8,DUMON,Du monde entier,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89
9,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,British Isles,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
10,FOLIG,Folies gourmandes,Martine Rancé,Assistant Sales Agent,"184, chaussée de Tournai",Lille,Western Europe,59000,France,20.16.10.16,20.16.10.17
11,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,München,Western Europe,80805,Germany,089-0877310,089-0877451
12,FRANR,France restauration,Carine Schmitt,Marketing Manager,"54, rue Royale",Nantes,Western Europe,44000,France,40.32.21.21,40.32.21.20
13,ISLAT,Island Trading,Helen Bennett,Marketing Manager,Garden House Crowther Way,Cowes,British Isles,PO31 7PJ,UK,(198) 555-8888,None
14,KOENE,Königlich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,Western Europe,14776,Germany,0555-09876,None
15,LACOR,La corne d'abondance,Daniel Tonini,Sales Representative,"67, avenue de l'Europe",Versailles,Western Europe,78000,France,30.59.84.10,30.59.85.11
16,LAMAI,La maison d'Asie,Annette Roulet,Sales Manager,1 rue Alsace-Lorraine,Toulouse,Western Europe,31000,France,61.77.61.10,61.77.61.11
17,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,Western Europe,60528,Germany,069-0245984,069-0245874
18,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,Western Europe,04179,Germany,0342-023176,None
19,NORTS,North/South,Simon Crowther,Sales Associate,South House 300 Queensbridge,London,British Isles,SW7 1RZ,UK,(171) 555-7733,(171) 555-2530
20,OTTIK,Ottilies Käseladen,Henriette Pfalzheim,Owner,Mehrheimerstr. 369,Köln,Western Europe,50739,Germany,0221-0644327,0221-0765721
21,PARIS,Paris spécialités,Marie Bertrand,Owner,"265, boulevard Charonne",Paris,Western Europe,75012,France,(1) 42.34.22.66,(1) 42.34.22.77
22,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstraße 10,Cunewalde,Western Europe,01307,Germany,0372-035188,None
23,SEVES,Seven Seas Imports,Hari Kumar,Sales Manager,90 Wadhurst Rd.,London,British Isles,OX15 4NB,UK,(171) 555-1717,(171) 555-5646
24,SPECD,Spécialités du monde,Dominique Perrier,Marketing Manager,"25, rue Lauriston",Paris,Western Europe,75016,France,(1) 47.55.60.10,(1) 47.55.60.20
25,TOMSP,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695
26,VICTE,Victuailles en stock,Mary Saveley,Sales Agent,"2, rue du Commerce",Lyon,Western Europe,69004,France,78.32.54.86,78.32.54.87
27,VINET,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
28,WANDK,Die Wandernde Kuh,Rita Müller,Sales Representative,Adenauerallee 900,Stuttgart,Western Europe,70563,Germany,0711-020361,0711-035428

Total matching records: 29

In [16]:
query7 = """
SELECT *
FROM Customers
WHERE Country NOT IN ('UK', 'Germany');
"""

result7 = pd.read_sql_query(query7, conn)
display(result7)
print("Total matching records:", len(result7))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
1,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
2,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
3,BLONP,Blondesddsl père et fils,Frédérique Citeaux,Marketing Manager,"24, place Kléber",Strasbourg,Western Europe,67000,France,88.60.15.31,88.60.15.32
4,BOLID,Bólido Comidas preparadas,Martín Sommer,Owner,"C/ Araquil, 67",Madrid,Southern Europe,28023,Spain,(91) 555 22 82,(91) 555 91 99
...,...,...,...,...,...,...,...,...,...,...,...
68,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,Scandinavia,90110,Finland,981-443655,981-443655
69,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,South America,08737-363,Brazil,(14) 555-8122,None
70,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,North America,98128,USA,(206) 555-4112,(206) 555-4115
71,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,Scandinavia,21240,Finland,90-224 8858,90-224 8858
72,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,Eastern Europe,01-012,Poland,(26) 642-7012,(26) 642-7012

Total matching records: 73

In [17]:
query8 = """
SELECT *
FROM Customers
WHERE CustomerID BETWEEN 3 AND 8;
"""

result8 = pd.read_sql_query(query8, conn)
display(result8)
print("Total matching records:", len(result8))

Empty DataFrame
Columns: [CustomerID, CompanyName, ContactName, ContactTitle, Address, City, Region, PostalCode, Country, Phone, Fax]
Index: []

Total matching records: 0

In [18]:
query9 = """
SELECT *
FROM Customers
WHERE CustomerID NOT BETWEEN 3 AND 8;
"""

result9 = pd.read_sql_query(query9, conn)
display(result9)
print("Total matching records:", len(result9))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...,...
88,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,Scandinavia,90110,Finland,981-443655,981-443655
89,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,South America,08737-363,Brazil,(14) 555-8122,None
90,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,North America,98128,USA,(206) 555-4112,(206) 555-4115
91,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,Scandinavia,21240,Finland,90-224 8858,90-224 8858
92,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,Eastern Europe,01-012,Poland,(26) 642-7012,(26) 642-7012

Total matching records: 93

In [19]:
query10 = """
SELECT *
FROM Customers
WHERE ContactName LIKE 'A%';
"""

result10 = pd.read_sql_query(query10, conn)
display(result10)
print("Total matching records:", len(result10))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
1,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
2,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,British Isles,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
3,FAMIA,Familia Arquibaldo,Aria Cruz,Marketing Assistant,"Rua Orós, 92",Sao Paulo,South America,05442-030,Brazil,(11) 555-9857,None
4,GOURL,Gourmet Lanchonetes,André Fonseca,Sales Associate,"Av. Brasil, 442",Campinas,South America,04876-786,Brazil,(11) 555-9482,None
5,LAMAI,La maison d'Asie,Annette Roulet,Sales Manager,1 rue Alsace-Lorraine,Toulouse,Western Europe,31000,France,61.77.61.10,61.77.61.11
6,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,Western Europe,04179,Germany,0342-023176,None
7,ROMEY,Romero y tomillo,Alejandra Camino,Accounting Manager,"Gran Vía, 1",Madrid,Southern Europe,28001,Spain,(91) 745 6200,(91) 745 6210
8,SPLIR,Split Rail Beer & Ale,Art Braunschweiger,Sales Manager,P.O. Box 555,Lander,North America,82520,USA,(307) 555-4680,(307) 555-6525
9,TRADH,Tradição Hipermercados,Anabela Domingues,Sales Representative,"Av. Inês de Castro, 414",Sao Paulo,South America,05634-030,Brazil,(11) 555-2167,(11) 555-2168

Total matching records: 10

In [20]:

query11 = """
SELECT *
FROM Customers
WHERE ContactName LIKE '%a';
"""

result11 = pd.read_sql_query(query11, conn)
display(result11)
print("Total matching records:", len(result11))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,GALED,Galería del gastrónomo,Eduardo Saavedra,Marketing Manager,"Rambla de Cataluña, 23",Barcelona,Southern Europe,08022,Spain,(93) 203 4560,(93) 203 4561
1,GOURL,Gourmet Lanchonetes,André Fonseca,Sales Associate,"Av. Brasil, 442",Campinas,South America,04876-786,Brazil,(11) 555-9482,None
2,GROSR,GROSELLA-Restaurante,Manuel Pereira,Owner,5ª Ave. Los Palos Grandes,Caracas,South America,1081,Venezuela,(2) 283-2951,(2) 283-3397
3,HUNGO,Hungry Owl All-Night Grocers,Patricia McKenna,Sales Associate,8 Johnstown Road,Cork,British Isles,None,Ireland,2967 542,2967 3333
4,OCEAN,Océano Atlántico Ltda.,Yvonne Moncada,Sales Agent,Ing. Gustavo Moncada 8585 Piso 20-A,Buenos Aires,South America,1010,Argentina,(1) 135-5333,(1) 135-5535
5,QUEDE,Que Delícia,Bernardo Batista,Accounting Manager,"Rua da Panificadora, 12",Rio de Janeiro,South America,02389-673,Brazil,(21) 555-4252,(21) 555-4545
6,RICAR,Ricardo Adocicados,Janete Limeira,Assistant Sales Agent,"Av. Copacabana, 267",Rio de Janeiro,South America,02389-890,Brazil,(21) 555-3412,None

Total matching records: 7

In [21]:

query12 = """
SELECT *
FROM Customers
WHERE ContactName LIKE '%an%';
"""

result12 = pd.read_sql_query(query12, conn)
display(result12)
print("Total matching records:", len(result12))

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
3,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,Western Europe,68306,Germany,0621-08460,0621-08924
4,BONAP,Bon app',Laurence Lebihan,Owner,"12, rue des Bouchers",Marseille,Western Europe,13008,France,91.24.45.40,91.24.45.41
5,CENTC,Centro comercial Moctezuma,Francisco Chang,Marketing Manager,Sierras de Granada 9993,México D.F.,Central America,05022,Mexico,(5) 555-3392,(5) 555-7293
6,CHOPS,Chop-suey Chinese,Yang Wang,Owner,Hauptstr. 29,Bern,Western Europe,3012,Switzerland,0452-076545,None
7,DUMON,Du monde entier,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89
8,EASTC,Eastern Connection,Ann Devon,Sales Agent,35 King George,London,British Isles,WX3 6FW,UK,(171) 555-0297,(171) 555-3373
9,ERNSH,Ernst Handel,Roland Mendel,Sales Manager,Kirchgasse 6,Graz,Western Europe,8010,Austria,7675-3425,7675-3426
10,FOLIG,Folies gourmandes,Martine Rancé,Assistant Sales Agent,"184, chaussée de Tournai",Lille,Western Europe,59000,France,20.16.10.16,20.16.10.17
11,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,München,Western Europe,80805,Germany,089-0877310,089-0877451
12,GOURL,Gourmet Lanchonetes,André Fonseca,Sales Associate,"Av. Brasil, 442",Campinas,South America,04876-786,Brazil,(11) 555-9482,None
13,GROSR,GROSELLA-Restaurante,Manuel Pereira,Owner,5ª Ave. Los Palos Grandes,Caracas,South America,1081,Venezuela,(2) 283-2951,(2) 283-3397
14,LACOR,La corne d'abondance,Daniel Tonini,Sales Representative,"67, avenue de l'Europe",Versailles,Western Europe,78000,France,30.59.84.10,30.59.85.11
15,LAMAI,La maison d'Asie,Annette Roulet,Sales Manager,1 rue Alsace-Lorraine,Toulouse,Western Europe,31000,France,61.77.61.10,61.77.61.11
16,LAUGB,Laughing Bacchus Wine Cellars,Yoshi Tannamuri,Marketing Assistant,1900 Oak St.,Vancouver,North America,V3F 2K1,Canada,(604) 555-3392,(604) 555-7293
17,LONEP,Lonesome Pine Restaurant,Fran Wilson,Sales Manager,89 Chiaroscuro Rd.,Portland,North America,97219,USA,(503) 555-9573,(503) 555-9646
18,MAGAA,Magazzini Alimentari Riuniti,Giovanni Rovelli,Marketing Manager,Via Ludovico il Moro 22,Bergamo,Southern Europe,24100,Italy,035-640230,035-640231
19,MEREP,Mère Paillarde,Jean Fresnière,Marketing Assistant,43 rue St. Laurent,Montréal,North America,H1J 1C3,Canada,(514) 555-8054,(514) 555-8055
20,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,Western Europe,04179,Germany,0342-023176,None
21,PARIS,Paris spécialités,Marie Bertrand,Owner,"265, boulevard Charonne",Paris,Western Europe,75012,France,(1) 42.34.22.66,(1) 42.34.22.77
22,RICAR,Ricardo Adocicados,Janete Limeira,Assistant Sales Agent,"Av. Copacabana, 267",Rio de Janeiro,South America,02389-890,Brazil,(21) 555-3412,None
23,ROMEY,Romero y tomillo,Alejandra Camino,Accounting Manager,"Gran Vía, 1",Madrid,Southern Europe,28001,Spain,(91) 745 6200,(91) 745 6210
24,TORTU,Tortuga Restaurante,Miguel Angel Paolino,Owner,Avda. Azteca 123,México D.F.,Central America,05033,Mexico,(5) 555-2933,None
25,TRADH,Tradição Hipermercados,Anabela Domingues,Sales Representative,"Av. Inês de Castro, 414",Sao Paulo,South America,05634-030,Brazil,(11) 555-2167,(11) 555-2168

Total matching records: 26

In [22]:

import os

os.makedirs("Task_22_Results", exist_ok=True)

queries = {
    "Query_01": query1,
    "Query_02": query2,
    "Query_03": query3,
    "Query_04": query4,
    "Query_05": query5,
    "Query_06": query6,
    "Query_07": query7,
    "Query_08": query8,
    "Query_09": query9,
    "Query_10": query10,
    "Query_11": query11,
    "Query_12": query12
}

for name, sql in queries.items():
    result = pd.read_sql_query(sql, conn)
    result.to_csv(
        f"Task_22_Results/{name}_Results.csv",
        index=False
    )

with open("Task_22_Results/SQL_Queries.txt", "w") as f:
    for name, sql in queries.items():
        f.write(f"{name}\n")
        f.write(sql.strip() + ";\n\n")

print("All 12 query results saved successfully!")

All 12 query results saved successfully!

In [23]:

from google.colab import files
import shutil

shutil.make_archive(
    "Task_22_Results",
    "zip",
    "Task_22_Results"
)

files.download("Task_22_Results.zip")