**## Text Cleaning Basics - Customer Data Cleaning**

In [1]:

import pandas as pd


df = pd.read_excel("/content/Task-26-Text-Cleaning-Dataset.xlsx")


cleaned_df = df.copy()


for col in ["Customer_Name", "City"]:
    cleaned_df[col] = (
        cleaned_df[col]
        .fillna("")
        .astype(str)
        .str.replace("\u00A0", " ", regex=False)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
        .str.title()
    )

# Show original data
print("BEFORE CLEANING")
display(df)

# Show cleaned data
print("AFTER CLEANING")
display(cleaned_df)

# Show before-and-after examples
comparison = pd.DataFrame({
    "Before_Name": df["Customer_Name"],
    "After_Name": cleaned_df["Customer_Name"],
    "Before_City": df["City"],
    "After_City": cleaned_df["City"]
})

print("BEFORE AND AFTER COMPARISON")
display(comparison)

# Save the final files
cleaned_df.to_csv("cleaned_customer_dataset.csv", index=False)
comparison.to_csv("before_after_examples.csv", index=False)

cleaned_df.to_excel("Task-26-Cleaned-Dataset.xlsx", index=False)

print("SUCCESS: All output files created!")

BEFORE CLEANING

   Customer_ID      Customer_Name             Email        City
0          101    amanda joseph    amanda@gmail.com   hyderabad
1          102       RAHUL SHARMA   rahul@gmail.com      mumbai
2          103        priya reddy   priya@gmail.com  VIJAYAWADA
3          104      Arjun   Kumar   arjun@gmail.com     chennai
4          105       sNEha pATEL    sneha@gmail.com        PUNE
5          106         anil kumar    anil@gmail.com   bengaluru
6          107      KAVYA  REDDY    kavya@gmail.com   HYDERABAD
7          108        rohit singh   rohit@gmail.com       delhi

AFTER CLEANING

   Customer_ID  Customer_Name             Email        City
0          101  Amanda Joseph  amanda@gmail.com   Hyderabad
1          102   Rahul Sharma   rahul@gmail.com      Mumbai
2          103    Priya Reddy   priya@gmail.com  Vijayawada
3          104    Arjun Kumar   arjun@gmail.com     Chennai
4          105    Sneha Patel   sneha@gmail.com        Pune
5          106     Anil Kumar    anil@gmail.com   Bengaluru
6          107    Kavya Reddy   kavya@gmail.com   Hyderabad
7          108    Rohit Singh   rohit@gmail.com       Delhi

BEFORE AND AFTER COMPARISON

         Before_Name     After_Name Before_City  After_City
0    amanda joseph    Amanda Joseph   hyderabad   Hyderabad
1       RAHUL SHARMA   Rahul Sharma      mumbai      Mumbai
2        priya reddy    Priya Reddy  VIJAYAWADA  Vijayawada
3      Arjun   Kumar    Arjun Kumar     chennai     Chennai
4       sNEha pATEL     Sneha Patel        PUNE        Pune
5         anil kumar     Anil Kumar   bengaluru   Bengaluru
6      KAVYA  REDDY     Kavya Reddy   HYDERABAD   Hyderabad
7        rohit singh    Rohit Singh       delhi       Delhi

SUCCESS: All output files created!