**## Import libraries**

In [1]:
import pandas as pd
import sqlite3
from IPython.display import display

**## Load the dataset**

In [2]:
df = pd.read_csv('/content/employees_dataset.csv')

print("Dataset loaded successfully!")
display(df)

Dataset loaded successfully!

   employee_id   name department  salary  age
0            1   Asha         IT   50000   24
1            2   Ravi         HR   40000   28
2            3  Priya         IT   60000   26
3            4  Kiran      Sales   35000   30
4            5   Neha         HR   45000   25
5            6  Arjun      Sales   55000   29
6            7  Meena         IT   65000   27
7            8  Rahul         HR   42000   31
8            9  Divya      Sales   48000   23
9           10  Vikas         IT   52000   32

**## Check dataset information**

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

Number of rows: 10
Number of columns: 5

Column names:
['employee_id', 'name', 'department', 'salary', 'age']

Missing values:
employee_id    0
name           0
department     0
salary         0
age            0
dtype: int64

**## Create SQL database and table**

In [4]:
conn = sqlite3.connect(':memory:')

df.to_sql('employees', conn, if_exists='replace', index=False)

print("SQL table created successfully!")

SQL table created successfully!

**## Display all employees**

In [5]:
query = """
SELECT *
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

   employee_id   name department  salary  age
0            1   Asha         IT   50000   24
1            2   Ravi         HR   40000   28
2            3  Priya         IT   60000   26
3            4  Kiran      Sales   35000   30
4            5   Neha         HR   45000   25
5            6  Arjun      Sales   55000   29
6            7  Meena         IT   65000   27
7            8  Rahul         HR   42000   31
8            9  Divya      Sales   48000   23
9           10  Vikas         IT   52000   32

**## COUNT(): Total number of employees**

In [6]:
query = """
SELECT COUNT(*) AS total_employees
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

   total_employees
0               10

**## SUM(): Total salary**

In [7]:
query = """
SELECT SUM(salary) AS total_salary
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

   total_salary
0        492000

**## AVG(): Average salary**

In [8]:
query = """
SELECT ROUND(AVG(salary), 2) AS average_salary
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

   average_salary
0         49200.0

**## MIN(): Minimum salary**

In [9]:
query = """
SELECT MIN(salary) AS minimum_salary
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

   minimum_salary
0           35000

**## MAX(): Maximum salary**

In [10]:
query = """
SELECT MAX(salary) AS maximum_salary
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

   maximum_salary
0           65000

**## GROUP BY: Employee count by department**

In [11]:
query = """
SELECT department, COUNT(*) AS employee_count
FROM employees
GROUP BY department
ORDER BY department;
"""

result = pd.read_sql_query(query, conn)
display(result)

  department  employee_count
0         HR               3
1         IT               4
2      Sales               3

**## GROUP BY: Employee count by department**

In [12]:
query = """
SELECT department, SUM(salary) AS total_salary
FROM employees
GROUP BY department
ORDER BY department;
"""

result = pd.read_sql_query(query, conn)
display(result)

  department  total_salary
0         HR        127000
1         IT        227000
2      Sales        138000

**## GROUP BY: Average salary by department**

In [13]:
query = """
SELECT department, ROUND(AVG(salary), 2) AS average_salary
FROM employees
GROUP BY department
ORDER BY department;
"""

result = pd.read_sql_query(query, conn)
display(result)

  department  average_salary
0         HR        42333.33
1         IT        56750.00
2      Sales        46000.00

**## MIN() and MAX() by department**

In [14]:
query = """
SELECT
    department,
    MIN(salary) AS minimum_salary,
    MAX(salary) AS maximum_salary
FROM employees
GROUP BY department
ORDER BY department;
"""

result = pd.read_sql_query(query, conn)
display(result)

  department  minimum_salary  maximum_salary
0         HR           40000           45000
1         IT           50000           65000
2      Sales           35000           55000

**##HAVING: Departments with average salary above 45000**

In [15]:
query = """
SELECT
    department,
    ROUND(AVG(salary), 2) AS average_salary
FROM employees
GROUP BY department
HAVING AVG(salary) > 45000
ORDER BY department;
"""

result = pd.read_sql_query(query, conn)
display(result)

  department  average_salary
0         IT         56750.0
1      Sales         46000.0

**## ORDER BY: Employees ranked by salary**

In [16]:
query = """
SELECT name, department, salary
FROM employees
ORDER BY salary DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

    name department  salary
0  Meena         IT   65000
1  Priya         IT   60000
2  Arjun      Sales   55000
3  Vikas         IT   52000
4   Asha         IT   50000
5  Divya      Sales   48000
6   Neha         HR   45000
7  Rahul         HR   42000
8   Ravi         HR   40000
9  Kiran      Sales   35000

**## Transaction and ROLLBACK**

In [17]:
cursor = conn.cursor()

cursor.execute("BEGIN TRANSACTION")

cursor.execute("""
INSERT INTO employees
(employee_id, name, department, salary, age)
VALUES (11, 'Temporary', 'IT', 30000, 22);
""")

print("After INSERT:")
print(pd.read_sql_query(
    "SELECT COUNT(*) AS total_employees FROM employees;",
    conn
))

conn.rollback()

print("\nAfter ROLLBACK:")
print(pd.read_sql_query(
    "SELECT COUNT(*) AS total_employees FROM employees;",
    conn
))

After INSERT:
   total_employees
0               11

After ROLLBACK:
   total_employees
0               10

**## Final summary of aggregate functions**

In [18]:
query = """
SELECT
    COUNT(*) AS total_employees,
    SUM(salary) AS total_salary,
    ROUND(AVG(salary), 2) AS average_salary,
    MIN(salary) AS minimum_salary,
    MAX(salary) AS maximum_salary
FROM employees;
"""

result = pd.read_sql_query(query, conn)
display(result)

,total_employees,total_salary,average_salary,minimum_salary,maximum_salary
0,10,492000,49200.0,35000,65000

**## Conclusion**

In [19]:
print("TASK 23: SQL AGGREGATION BASICS")
print("--------------------------------")
print("1. COUNT() - Counts the employees")
print("2. SUM()   - Calculates total salary")
print("3. AVG()   - Calculates average salary")
print("4. MIN()   - Finds minimum salary")
print("5. MAX()   - Finds maximum salary")
print("6. GROUP BY - Groups employees by department")
print("7. HAVING  - Filters grouped results")
print("8. ROLLBACK - Cancels the temporary transaction")
print("--------------------------------")
print("Task completed successfully!")

TASK 23: SQL AGGREGATION BASICS
--------------------------------
1. COUNT() - Counts the employees
2. SUM()   - Calculates total salary
3. AVG()   - Calculates average salary
4. MIN()   - Finds minimum salary
5. MAX()   - Finds maximum salary
6. GROUP BY - Groups employees by department
7. HAVING  - Filters grouped results
8. ROLLBACK - Cancels the temporary transaction
--------------------------------
Task completed successfully!