**## Upload datasets**

In [1]:
from google.colab import files

uploaded = files.upload()

Saving customers.csv to customers.csv
Saving products.csv to products.csv

**## Import libraries**

In [2]:
import sqlite3
import pandas as pd
from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!

**## Read datasets**

In [3]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")

print("Customers loaded:", len(customers))
print("Products loaded:", len(products))

print("\nCustomers columns:")
print(customers.columns.tolist())

print("\nProducts columns:")
print(products.columns.tolist())

Customers loaded: 10
Products loaded: 12

Customers columns:
['CustomerID', 'CompanyName', 'City', 'Country']

Products columns:
['ProductID', 'ProductName', 'UnitPrice', 'UnitsInStock']

**## Create database**

In [4]:
conn = sqlite3.connect(":memory:")

customers.to_sql(
    "Customers", conn, index=False, if_exists="replace"
)

products.to_sql(
    "Products", conn, index=False, if_exists="replace"
)

print("Database created successfully!")

Database created successfully!

**## Query 1: Display all customers**

In [5]:
query = """
SELECT *
FROM Customers;
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID                         CompanyName         City  Country
0      ALFKI                 Alfreds Futterkiste       Berlin  Germany
1      ANATR  Ana Trujillo Emparedados y helados  Mexico D.F.   Mexico
2      ANTON             Antonio Moreno Taquería  Mexico D.F.   Mexico
3      AROUT                     Around the Horn       London       UK
4      BERGS                  Berglunds snabbköp        Luleå   Sweden
5      BLAUS             Blauer See Delikatessen     Mannheim  Germany
6      BLONP            Blondesddsl père et fils   Strasbourg   France
7      BOLID           Bólido Comidas preparadas       Madrid    Spain
8      BONAP                            Bon app'    Marseille   France
9      BOTTM               Bottom-Dollar Markets    Tsawassen   Canada

**## Query 2: Select customer details**

In [6]:
query = """
SELECT CustomerID, CompanyName, City, Country
FROM Customers;
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID                         CompanyName         City  Country
0      ALFKI                 Alfreds Futterkiste       Berlin  Germany
1      ANATR  Ana Trujillo Emparedados y helados  Mexico D.F.   Mexico
2      ANTON             Antonio Moreno Taquería  Mexico D.F.   Mexico
3      AROUT                     Around the Horn       London       UK
4      BERGS                  Berglunds snabbköp        Luleå   Sweden
5      BLAUS             Blauer See Delikatessen     Mannheim  Germany
6      BLONP            Blondesddsl père et fils   Strasbourg   France
7      BOLID           Bólido Comidas preparadas       Madrid    Spain
8      BONAP                            Bon app'    Marseille   France
9      BOTTM               Bottom-Dollar Markets    Tsawassen   Canada

**## Query 3: Customers from London**

In [7]:
query = """
SELECT CustomerID, CompanyName, City
FROM Customers
WHERE City = 'London';
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID      CompanyName    City
0      AROUT  Around the Horn  London

**## Query 4: Customers from Germany**

In [8]:
query = """
SELECT CustomerID, CompanyName, Country
FROM Customers
WHERE Country = 'Germany';
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID              CompanyName  Country
0      ALFKI      Alfreds Futterkiste  Germany
1      BLAUS  Blauer See Delikatessen  Germany

**## Query 5: Sort customers by company name**

In [9]:
query = """
SELECT CustomerID, CompanyName, Country
FROM Customers
ORDER BY CompanyName ASC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID                         CompanyName  Country
0      ALFKI                 Alfreds Futterkiste  Germany
1      ANATR  Ana Trujillo Emparedados y helados   Mexico
2      ANTON             Antonio Moreno Taquería   Mexico
3      AROUT                     Around the Horn       UK
4      BERGS                  Berglunds snabbköp   Sweden
5      BLAUS             Blauer See Delikatessen  Germany
6      BLONP            Blondesddsl père et fils   France
7      BONAP                            Bon app'   France
8      BOTTM               Bottom-Dollar Markets   Canada
9      BOLID           Bólido Comidas preparadas    Spain

**## Query 5: Sort customers by company name**

In [10]:
query = """
SELECT *
FROM Products;
"""

result = pd.read_sql_query(query, conn)
display(result)

    ProductID                      ProductName  UnitPrice  UnitsInStock
0           1                             Chai      18.00            39
1           2                            Chang      19.00            17
2           3                    Aniseed Syrup      10.00            13
3           4     Chef Anton's Cajun Seasoning      22.00            53
4           5           Chef Anton's Gumbo Mix      21.35             0
5           6     Grandma's Boysenberry Spread      25.00           120
6           7  Uncle Bob's Organic Dried Pears      30.00            15
7           8       Northwoods Cranberry Sauce      40.00             6
8           9                  Mishi Kobe Niku      97.00            29
9          10                            Ikura      31.00            31
10         11                   Queso Cabrales      21.00            22
11         12                            Konbu       6.00            24

**## Query 6: Display all products**

In [11]:
query = """
SELECT ProductID, ProductName, UnitPrice
FROM Products
WHERE UnitPrice < 20;
"""

result = pd.read_sql_query(query, conn)
display(result)

   ProductID    ProductName  UnitPrice
0          1           Chai       18.0
1          2          Chang       19.0
2          3  Aniseed Syrup       10.0
3         12          Konbu        6.0

**## Query 7: Products priced below 20**

In [12]:
query = """
SELECT ProductID, ProductName, UnitPrice
FROM Products
WHERE UnitPrice > 20;
"""

result = pd.read_sql_query(query, conn)
display(result)

   ProductID                      ProductName  UnitPrice
0          4     Chef Anton's Cajun Seasoning      22.00
1          5           Chef Anton's Gumbo Mix      21.35
2          6     Grandma's Boysenberry Spread      25.00
3          7  Uncle Bob's Organic Dried Pears      30.00
4          8       Northwoods Cranberry Sauce      40.00
5          9                  Mishi Kobe Niku      97.00
6         10                            Ikura      31.00
7         11                   Queso Cabrales      21.00

**## Query 8: Products priced above 20**

In [13]:
query = """
SELECT ProductID, ProductName, UnitPrice
FROM Products
ORDER BY UnitPrice DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

    ProductID                      ProductName  UnitPrice
0           9                  Mishi Kobe Niku      97.00
1           8       Northwoods Cranberry Sauce      40.00
2          10                            Ikura      31.00
3           7  Uncle Bob's Organic Dried Pears      30.00
4           6     Grandma's Boysenberry Spread      25.00
5           4     Chef Anton's Cajun Seasoning      22.00
6           5           Chef Anton's Gumbo Mix      21.35
7          11                   Queso Cabrales      21.00
8           2                            Chang      19.00
9           1                             Chai      18.00
10          3                    Aniseed Syrup      10.00
11         12                            Konbu       6.00

**## Query 9: Sort products by highest price**

In [14]:
query = """
SELECT ProductID, ProductName, UnitPrice
FROM Products
ORDER BY UnitPrice ASC
LIMIT 5;
"""

result = pd.read_sql_query(query, conn)
display(result)

   ProductID     ProductName  UnitPrice
0         12           Konbu        6.0
1          3   Aniseed Syrup       10.0
2          1            Chai       18.0
3          2           Chang       19.0
4         11  Queso Cabrales       21.0

**## Query 10: Five cheapest products**

In [15]:
print("TASK 21: BASIC SQL SELECT")
print("-------------------------")
print("Customers:", len(customers))
print("Products:", len(products))
print("SQL queries completed: 10")
print("Status: Completed")

TASK 21: BASIC SQL SELECT
-------------------------
Customers: 10
Products: 12
SQL queries completed: 10
Status: Completed